#!/usr/bin/env ruby

require "clap"
require "webtask/cli"

Clap.run ARGV,
  "-b" => lambda { |bind| Webtask::CLI.instance.bind = bind },
  "-p" => lambda { |port| Webtask::CLI.instance.port = Integer(port) },
  "-h" => lambda { Webtask::CLI.instance.show_help }

require "webtask"
Webtask::Application.run!
